/**
 * KATA Architecture - Data Factory
 *
 * Generador centralizado de datos de prueba.
 * Regla de oro: NUNCA datos estáticos, siempre dinámicos con Faker.
 *
 * Acceso:
 *   - Desde componentes: this.data.createUser()
 *   - Import directo: import { DataFactory } from '@DataFactory'
 */

import type {
  TestAcceptanceCriterion,
  TestCredentials,
  TestModule,
  TestProject,
  TestUser,
  TestUserStory,
  TestWorkspace,
} from './types';

import { faker } from '@faker-js/faker';

export class DataFactory {
  // ============================================
  // HELPERS PRIVADOS
  // ============================================

  private static uniqueId(): string {
    return `${Date.now()}-${faker.string.alphanumeric(6)}`;
  }

  private static testEmail(prefix = 'test'): string {
    const id = faker.string.alphanumeric(6).toLowerCase();
    const name = faker.person.firstName().toLowerCase();
    return `${prefix}.${name}.${id}@example.com`;
  }

  private static securePassword(): string {
    return `Test${faker.string.alphanumeric(8)}!`;
  }

  // ============================================
  // GENERADORES PRINCIPALES
  // ============================================

  /**
   * Genera un usuario completo para testing
   * @param overrides - Propiedades a sobreescribir
   */
  static createUser(overrides?: Partial<TestUser>): TestUser {
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();

    return {
      email: this.testEmail(),
      password: this.securePassword(),
      name: `${firstName} ${lastName}`,
      firstName,
      lastName,
      ...overrides,
    };
  }

  /**
   * Genera solo credenciales (email + password)
   * @param overrides - Propiedades a sobreescribir
   */
  static createCredentials(overrides?: Partial<TestCredentials>): TestCredentials {
    return {
      email: this.testEmail(),
      password: this.securePassword(),
      ...overrides,
    };
  }

  /**
   * Genera un ID único para identificar datos de test
   * Útil para cleanup y trazabilidad
   */
  static createTestId(prefix = 'test'): string {
    return `${prefix}-${this.uniqueId()}`;
  }

  // ============================================
  // BUNKAI DOMAIN DATA
  // ============================================

  static createWorkspace(overrides?: Partial<TestWorkspace>): TestWorkspace {
    const id = this.uniqueId().toLowerCase();
    return {
      name: `QA Workspace ${id}`,
      slug: `qa-workspace-${id}`,
      ...overrides,
    };
  }

  static createProject(overrides?: Partial<TestProject>): TestProject {
    const id = this.uniqueId().toLowerCase();
    return {
      name: `QA Project ${id}`,
      slug: `qa-project-${id}`,
      description: 'Project generated by KATA test data factory.',
      ...overrides,
    };
  }

  static createModule(overrides?: Partial<TestModule>): TestModule {
    return {
      name: `QA Module ${this.uniqueId()}`,
      description: 'Module generated by KATA test data factory.',
      ...overrides,
    };
  }

  static createUserStory(overrides?: Partial<TestUserStory>): TestUserStory {
    return {
      title: `As a QA engineer I can validate ${faker.word.words(3)}`,
      description: 'Story generated by KATA test data factory.',
      jiraKey: `BK-${faker.number.int({ min: 1000, max: 9999 })}`,
      ...overrides,
    };
  }

  static createAcceptanceCriterion(overrides?: Partial<TestAcceptanceCriterion>): TestAcceptanceCriterion {
    return {
      text: `Given valid context, when ${faker.word.words(3)}, then Bunkai preserves traceability.`,
      ...overrides,
    };
  }
}

export default DataFactory;
